#!/usr/bin/expect

set timeout -1

set rsa_pub_file    [lindex $argv 0]
set host_ip         [lindex $argv 1]
set port            [lindex $argv 2]
set user_name       [lindex $argv 3]
set password        [lindex $argv 4]

spawn ssh-copy-id -i ${rsa_pub_file} "${user_name}@${host_ip}"

expect {
  "*yes/no*"    { send "yes\r";exp_continue }
  "*password*"  { send "${password}\r";exp_continue }
}
